### ISSUE TITLE
Wrong conversion from hex color string values

### ISSUE THREAD

**Issue by codetrix** [nikeee/dot-language-support#22]
There is a bug in the color conversion code when converting from a hex color string into a `Color` object.

The bug manifests itself (on edotor.net) as:
1. wrong color squares next to hex type color strings (for most part of the color range).
2. wrong color being used for the currently selected color in the color picker when hovering over a hex type color string 

Running this code snippet within the `colorProvider.ts` will show the bug 
```typescript
console.log(getColorStringFromColor(getHexCodeColor("#000000")))
console.log(getColorStringFromColor(getHexCodeColor("#ffffff")))
console.log(getColorStringFromColor(getHexCodeColor("#ff7f14")))
console.log(getColorStringFromColor(getHexCodeColor("#ff0000")))
console.log(getColorStringFromColor(getHexCodeColor("#00345678")))
console.log(getColorStringFromColor(getHexCodeColor("#ffabcdef")))
```
The expected output is
```text
#000000
#ffffff
#ff7f14
#ff0000
#345678  // because getColorStringFromColor ignores alpha
#abcdef  // because getColorStringFromColor ignores alpha
```
The actual output produced by the current version of the code is
```text
#000000
#ff0000ff00ff
#ff00007f0014
#ff00000000
#340000560078
#ab0000cd00ef
```

The lines
https://github.com/nikeee/dot-language-support/blob/4380503573fc5bf4ac62f3e6d4d24afec536f498/src/service/colorProvider.ts#L69-L75

Should be changed to
```typescript
    const colorInt = parseInt(hexCode, 16); 
    return { 
 	red: (colorInt >> 16 & 0xff) / 255.0, 
 	green: (colorInt >> 8 & 0xff) / 255.0, 
 	blue: (colorInt & 0xff) / 255.0, 
 	alpha: hexCode.length === 8 ? (colorInt >> 24 & 0xff) / 255.0 : 1.0, 
     };
```

Running the code snippet again with the suggested patch applied generates the expected output 
```text
#000000
#ffffff
#ff7f14
#ff0000
#345678
#abcdef
```

**Comment by codetrix** [comment]
Opened PR #23 that has the above fix (but I think I messed the auto link commit message)

**Comment by nikeee** [comment]
Thanks for the fix!
Don't know what was in my head when decoding the integer.
